# Generated by Django 6.0 on 2025-12-23 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffprofile_mobile_number_alter_staffprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='mobile_number',
            field=models.CharField(help_text='Enter 10-digit mobile number', max_length=10, validators=[django.core.validators.RegexValidator(message='Mobile number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
