# Generated by Django 6.0 on 2025-12-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_staffprofile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
    ]
