# Generated by Django 6.0 on 2025-12-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_staffprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
    ]
