# Generated by Django 6.0 on 2025-12-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_staffprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_category',
            field=models.CharField(choices=[('SECURITY', 'Security'), ('HOUSEKEEPING', 'Housekeeping'), ('CANTEEN', 'Canteen'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
