# Generated by Django 5.2.9 on 2025-12-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_geofence_id_alter_locationlog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationlog',
            name='is_location_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
