# Generated by Django 6.0 on 2025-12-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locationlog_is_location_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofence',
            name='name',
            field=models.CharField(default='Campus', max_length=100),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='radius_meters',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='locationlog',
            name='is_location_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
