# Generated by Django 5.2.9 on 2025-12-26 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_staffprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
